name: Rerun block_if_release on release branch creation
env:
  RELEASE_BRANCH_PREFIX: release-v

on: create

jobs:
  rerun-block-if-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check if ref is release branch
        id: check_release_branch
        run: |
          echo "Event: ${{ github.event_name }}"
          echo "Ref: ${{ github.ref }}"
          echo "Ref type: ${{ github.event.ref_type }}"  # branch or tag
          if [[ "${{ github.event.ref_type }}" == "branch" && "${{ github.ref }}" == "refs/heads/${RELEASE_BRANCH_PREFIX}"* ]]; then
            echo "is_release_branch=true" >> $GITHUB_OUTPUT
          else
            echo "is_release_branch=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger block_if_release on open PRs
        id: trigger
        if: steps.check_release_branch.outputs.is_release_branch == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const prs = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open'
            });
            for (const pr of prs.data) {
              await github.rest.actions.reRunWorkflow({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: pr.head.sha // This may need adjustment; see note below
              });
            }
